import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SWRConfig } from "swr";
import "./globals.css";
import { StoreProvider } from "./contexts/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // localStorage.theme = "dark";

  return (
    <StoreProvider>
      <html className="light" lang="en" data-shade="900" data-rounded="large">
        <head>
          <meta
            charSet="UTF-8"
            name="format-detection"
            content="telephone=no, date=no, email=no, address=no"
          />
          <link
            rel="icon"
            type="image/svg+xml"
            href="/favicon.svg"
            media="(prefers-color-scheme: light)"
          />
          <link
            rel="icon"
            type="image/svg+xml"
            href="/darkfavicon.svg"
            media="(prefers-color-scheme: dark)"
          />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
          <title>Tailus UI React</title>
        </head>
        {/* Layout UI */}
        <body className="body bg-gray-50 dark:bg-gray-950">
          <SWRConfig>{children}</SWRConfig>
        </body>
      </html>
    </StoreProvider>
  );
}
